### ISSUE TITLE
feat :  🚀  Stable Version of Bitbucket Connector with API Token Auth Strategy

### ISSUE THREAD

**Issue by Vivek-Lahole** [OcularEngineering/ocular#154]
## 🎯 Goal

Develop a stable version of the Bitbucket connector that supports API Token authentication. This feature aims to enhance security and simplify the authentication process for users.

### API Token Authentication

The Bitbucket connector should support API Token authentication to enhance security. Users can generate their API tokens from Bitbucket and use them to authenticate their sessions. This method is not only more secure but also reduces the hassle of managing passwords.

### API Token UI for User Input

Develop a user-friendly interface where users can input their API Tokens. This UI should be intuitive, guiding users through the process of copying their API token from Bitbucket and pasting it into the connector configuration. Clear instructions and error messages should be provided to ensure a seamless experience.

## 🔍 Example Usage

1. **User Interface**: 
   - Users navigate to the settings page and find the API Token input field.
   - Users enter their API Token and save the configuration.
   
2. **Authentication**: 
   - The connector uses the provided API Token to authenticate requests to Bitbucket.

3. **Error Handling**: 
   - If an error occurs, the system logs the error 

### Additional context

# 📄 Note for Contributors

Contributors are encouraged to take reference from other apps for file naming, folder structure, and coding style. Following consistent practices ensures code readability, maintainability, and a seamless development experience.

## 📁 File Naming and Folder Structure

- **Consistency**: Maintain a consistent naming convention across files and folders.
- **Clarity**: Choose names that clearly describe the purpose and contents of the files or folders.
- **Organization**: Structure folders logically to group related files together.

## 💻 Coding Style

- **Readability**: Write clean and readable code, following established coding standards.
- **Documentation**: Include comments and documentation where necessary to explain complex logic.
- **Best Practices**: Adhere to best practices in coding to ensure code quality and maintainability.

## 🔍 Examples

To ensure uniformity, look at examples from other well-structured apps within the project. These can provide valuable insights into effective file naming, folder structuring, and coding styles.

## 📢 Communication

If you have any questions or need further clarification, feel free to reach out to the team. Collaboration and open communication are key to successful project development.

Thank you for your contributions and efforts in maintaining high standards!

✨ Happy Coding! ✨

**Comment by louismurerwa** [comment]
thanks @Vivek-Lahole for writing down the detailed issues!

**Comment by hiteshwadhwani** [comment]
I have raised a PR #163  for the feature @Vivek-Lahole please can you review
